### ISSUE TITLE
Support for reverse proxy for web portal

### ISSUE THREAD

**Issue by ravensorb** [netbootxyz/webapp#4]
It would be great if there was a way to set the base url for the web interface -- this would allow it to work behind a reverse proxy or via a sub application

Ex: 192.168.1.2/web -> 192.168.10.2:3000

**Comment by thelamer** [comment]
Relevant lines:
https://github.com/netbootxyz/webapp/blob/master/app.js#L34-L40
Need to if a env var and sub it into the paths if exists.

**Comment by ravensorb** [comment]
Question -- would it make sense to move the web portal behind nginix rather than having it run on a custom port?

**Comment by thelamer** [comment]
The app uses socket.io to communicate on the backend , it is still possible to pipe through Nginx, but I really don't want to support that. Express server is reliable enough for this containers usecase.

**Comment by ravensorb** [comment]
Fair enough -- being able to set a value for a reverse proxy base url would be good too.

**Comment by thelamer** [comment]
Fixed in latest release, still need to add docs to the downstream repo for the new `SUBFOLDER` env variable. 
https://github.com/linuxserver/docker-netbootxyz
