### ISSUE TITLE
Netbootxyz can wipeout itself :) 

### ISSUE THREAD

**Issue by Marszczak** [netbootxyz/webapp#55]
Funny thing - there is untracked asset section in the local asset part of the web interface. I have set volumes for config and assets to the very same folder. As a result I can see menu related files under untracked assets. From there I can click select all and delete. And voila - no more working netbootxyz menus :):)
Fortunately it is very easy to redeploy from docker image.

**Comment by antonym** [comment]
I'd keep them in separate folders then. :D
