### ISSUE TITLE
Some required files improperly categorized as "untracked" in Local Assets

### ISSUE THREAD

**Issue by bastropsteve** [netbootxyz/webapp#6]
When downloading the required files for certain distributions, the .part2 files needed for squashfs (and similar) are not recognized by the webapp as being part of the various distributions, and are therefore marked as "untracked".  Example here:

![image](https://user-images.githubusercontent.com/77296063/104224756-08909a80-540b-11eb-8da9-3d8254e71e2f.png)

The first of these "untracked assets" is part of the needed two-part airootfs for Bluestar:

![image](https://user-images.githubusercontent.com/77296063/104224878-2fe76780-540b-11eb-8c23-9dd9649812b2.png)

Perhaps this is simply a matter of accepting .part2 files as an accepted file suffix.

**Comment by thelamer** [comment]
Fixed in latest release
